---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: debian9
    box: generic/debian9
    memory: 2048
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8020"
  - name: centos7
    box: generic/centos7
    memory: 2048
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8022"
provisioner:
  name: ansible
  env:
    # Allows placing roles in whatever path
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
