---
- name: Deploy web page using Ansible and Docker
  hosts: localhost
  gather_facts: true
  vars:
    docker_network_name: my_network
    docker_container_name: my_web_page
    application_port: 8080
  tasks:
    - name: Check Docker service status
      ansible.builtin.systemd_service:
        name: docker
        state: started
      register: docker_service_status

    - name: Fail the playbook if Docker is not running
      ansible.builtin.fail:
        msg: Docker service is not running on the target host.
      when: docker_service_status.failed

    - name: Create temporary directory
      ansible.builtin.tempfile:
        path: /tmp
        state: directory
        prefix: web_deploy_
      register: temp_dir

    - name: Set permissions for temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        mode: "0755"

    - name: Copy index.html file
      ansible.builtin.copy:
        content: |
          <html>
          <head>
            <title>Hello World!</title>
          </head>
          <body>
            <h1>Hello world! I was deployed using Ansible.</h1>
          </body>
          </html>
        dest: "{{ temp_dir.path }}/index.html"
        mode: "0644"

    - name: Create a network for Docker containers
      community.docker.docker_network:
        name: "{{ docker_network_name }}"
        state: present

    - name: Create Docker container for web page
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        image: nginxinc/nginx-unprivileged:1.25.2-alpine
        state: started
        published_ports:
          - "{{ application_port }}:8080"
        volumes:
          - "{{ temp_dir.path }}:/usr/share/nginx/html"
        networks:
          - name: "{{ docker_network_name }}"
            aliases: my_network
        healthcheck:
          # trunk-ignore(yamllint/quoted-strings)
          test: ["CMD", "curl", "--fail", "http://localhost:{{ application_port }}/"]
          start_period: 30s

    - name: Wait for Nginx container to start
      ansible.builtin.wait_for:
        host: localhost
        port: "{{ application_port }}"
        timeout: 30
        state: started

    # trunk-ignore(checkov/CKV2_ANSIBLE_1)
    - name: Test if web page is accessible
      ansible.builtin.uri:
        url: "http://localhost:{{ application_port }}/"
        return_content: true
      register: webpage_acessible
      delay: 2
      retries: 10
      until: webpage_acessible.status == 200
      failed_when: "'Hello world! I was deployed using Ansible.' not in webpage_acessible.content"

    - name: Display website URL
      ansible.builtin.debug:
        msg: "Web page deployed successfully! Access it at http://localhost:{{ application_port }}/"
